"""Tests for the sensor platform."""
from __future__ import annotations

import pytest
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er

from custom_components.localthings.const import DOMAIN


async def test_sensors_registered(
    hass: HomeAssistant, mock_entry, mock_coordinator_session
) -> None:
    """Sensors are registered for all SensorDesc entities in the fridge fixture."""
    await hass.config_entries.async_setup(mock_entry.entry_id)
    await hass.async_block_till_done()

    ent_reg = er.async_get(hass)
    entries = er.async_entries_for_config_entry(ent_reg, mock_entry.entry_id)
    sensor_entries = [e for e in entries if e.domain == 'sensor']
    assert sensor_entries, "Expected at least one sensor entity"


async def test_sensor_state_from_coordinator(
    hass: HomeAssistant, mock_entry, mock_coordinator_session
) -> None:
    """A temperature sensor reads its value from coordinator.data.

    Entity IDs are auto-generated by HA and don't embed capability path
    segments, so we filter by the mdi:thermometer icon that the fridge
    capability assigns to current-temperature sensors.
    """
    await hass.config_entries.async_setup(mock_entry.entry_id)
    await hass.async_block_till_done()

    states = hass.states.async_all('sensor')
    temp_states = [
        s for s in states
        if s.attributes.get('icon') == 'mdi:thermometer'
    ]
    assert temp_states, (
        f"No thermometer sensor found. Sensors: {[s.entity_id for s in states]}"
    )
    state = temp_states[0]
    assert state.state not in ('unknown', 'unavailable'), (
        f"Sensor state is {state.state}"
    )
